FROM node:14-alpine as builder
RUN apk update && apk add yarn 
RUN mkdir app
WORKDIR /app

COPY package*.json ./
RUN yarn install --network-timeout 1000000000

COPY . ./
RUN mv .env.development .env 
RUN cat .env
RUN yarn build

FROM nginx:alpine
COPY --from=builder /app/build /build
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
