import {
  DashboardRounded,
  SettingsRounded,
  PeopleRounded,
  PersonRounded,
  RestaurantRounded,
  LocalGroceryStoreRounded,
  GpsFixedRounded,
  AccountCircleRounded,
  StorefrontRounded,
  InsertDriveFileRounded,
  NotificationsRounded,
} from "@mui/icons-material";
import { useSelector } from "react-redux";

const useSidebarElements = () => {
  const name = useSelector((state) => state.auth.name);

  const menu = [
    {
      id: "dashboard",
      title: "dashboard",
      path: "/home/dashboard",
      isActive: false,
      icon: DashboardRounded,
      redirect: "/home/dashboard/orders",
      permission: "dashboard",
      children: [
        {
          id: "dashboard.orders",
          title: "orders",
          path: "/home/dashboard/orders",
          isActive: false,
          permission: "dashboard",
          isChild: true,
        },
        {
          id: "dashboard.clients",
          title: "clients",
          path: "/home/dashboard/clients",
          isActive: false,
          permission: "dashboard",
          isChild: true,
        },
        {
          id: "dashboard.products",
          title: "products",
          path: "/home/dashboard/products",
          isActive: false,
          permission: "dashboard",
          isChild: true,
        },
        {
          id: "dashboard.tops",
          title: "employees",
          path: "/home/dashboard/employees",
          isActive: false,
          permission: "dashboard",
          isChild: true,
        },
      ],
    },
    {
      id: "orders",
      title: "orders",
      path: "/home/orders",
      isActive: false,
      icon: LocalGroceryStoreRounded,
      permission: "order",
    },
    {
      id: "client",
      title: "clients",
      path: "/home/clients",
      isActive: true,
      icon: PeopleRounded,
      permission: "client",
    },
    {
      id: "personal",
      title: "personal",
      isActive: true,
      path: "/home/personal",
      redirect: "/home/personal/operator",
      permission: "operator",
      icon: PersonRounded,
      children: [
        {
          id: "person",
          title: "operator",
          path: "/home/personal/operator",
          isActive: true,
          permission: "operator",
        },
        {
          id: "couriers",
          title: "couriers",
          path: "/home/personal/couriers/list",
          isActive: false,
          permission: "courier",
          isChild: true,
          children: [
            {
              id: "courier",
              title: "courier",
              path: "/home/personal/couriers/list",
              isActive: false,
              permission: "courier",
              isChild: true,
            },
            {
              id: "courier",
              title: "courier.type",
              path: "/home/personal/couriers/courier-type",
              isActive: false,
              permission: "courier_type",
              isChild: true,
            },
            {
              id: "courier",
              title: "courier.fare",
              path: "/home/personal/couriers/courier-fare",
              isActive: false,
              permission: "courier_type",
              isChild: true,
            },
            {
              id: "courier",
              title: "courier.attendance",
              path: "/home/personal/couriers/courier-attendance",
              isActive: false,
              permission: "courier_type",
              isChild: true,
            },
            {
              id: "courier",
              title: "courier.bonus-penalty",
              path: "/home/personal/couriers/courier-bonus-penalty",
              isActive: false,
              permission: "courier_type",
              isChild: true,
            },
          ],
        },
      ],
    },
    {
      id: "catalog",
      title: "catalog",
      path: "/home/catalog",
      redirect: "/home/catalog/menu",
      isActive: false,
      icon: RestaurantRounded,
      permission: "product",
      children: [
        {
          id: "menu",
          title: "menu",
          path: "/home/catalog/menu",
          isChild: true,
          isActive: false,
          permission: "product",
        },
        {
          id: "goods.settings",
          title: "goods",
          path: "/home/catalog/goods",
          isChild: true,
          isActive: false,
          permission: "product",
        },
        {
          id: "category.settings",
          title: "category",
          path: "/home/catalog/category",
          isChild: true,
          isActive: false,
          permission: "product",
        },
        {
          id: "attributes.settings",
          title: "attributes",
          path: "/home/catalog/attributes",
          isChild: true,
          isActive: false,
          permission: "product",
        },
        {
          id: "brands.settings",
          title: "brands",
          path: "/home/catalog/brands",
          isChild: true,
          isActive: false,
          permission: "brands",
        },
        {
          id: "units.settings",
          title: "unit",
          path: "/home/catalog/units",
          isChild: true,
          isActive: false,
          permission: "units",
        },
        {
          id: "tags.settings",
          title: "tags",
          path: "/home/catalog/tags",
          isChild: true,
          isActive: false,
          permission: "tags",
        },
        {
          id: "ABCXYZ",
          title: "ABC-XYZ",
          path: "/home/catalog/abcxyz",
          isChild: true,
          isActive: false,
          permission: "product",
        },
      ],
    },
    {
      id: "marketing",
      title: "marketing",
      path: "/home/marketing",
      redirect: "/home/marketing/stocks",
      isActive: true,
      icon: GpsFixedRounded,
      permission: "promotion",
      children: [
        {
          id: "stock",
          title: "stock",
          path: "/home/marketing/stocks",
          isChild: true,
          isActive: false,
          permission: "promotion",
        },
        {
          id: "sms_sending",
          title: "sms_sending",
          path: "/home/marketing/sms-sending",
          isChild: true,
          isActive: false,
          permission: "promotion",
        },
        {
          id: "notification_to_apps",
          title: "notification_to_apps",
          path: "/home/marketing/notification-to-apps",
          isChild: true,
          isActive: false,
          permission: "promotion",
        },
        {
          id: "popup",
          title: "pop.up",
          path: "/home/marketing/popup",
          isChild: true,
          isActive: false,
          permission: "promotion",
        },
        {
          id: "banners",
          title: "banners",
          path: "/home/marketing/banners",
          isChild: true,
          isActive: false,
          permission: "promotion",
        },
        {
          id: "telegram-post",
          title: "telegram.post",
          path: "/home/marketing/telegram-post",
          isActive: false,
          permission: "promotion",
          isChild: true,
        },
        {
          id: "news",
          title: "news",
          path: "/home/marketing/news",
          isActive: false,
          permission: "promotion",
          isChild: true,
        },
        {
          id: "gallery",
          title: "events",
          path: "/home/marketing/gallery",
          isActive: false,
          permission: "promotion",
          isChild: true,
        },
        {
          id: "vacancies",
          title: "vacancies",
          path: "/home/marketing/vacancies",
          isActive: false,
          permission: "promotion",
          isChild: true,
        },
      ],
    },
    {
      id: "kitchen",
      title: "orders",
      path: "/home/kitchen",
      isActive: false,
      permission: "kitchen",
      icon: StorefrontRounded,
    },
    {
      id: "reports",
      title: "reports",
      path: "/home/reports",
      isActive: true,
      icon: InsertDriveFileRounded,
      permission: "report",
      redirect: "/home/reports/all_report",
      children: [
        {
          id: "all_report",
          title: "all_report",
          path: "/home/reports/all_report",
          isActive: false,
          permission: "report",
          isChild: true,
        },
        // {
        //   id: "gpt-report",
        //   title: "gpt-report",
        //   path: "/home/reports/gpt-report",
        //   isActive: false,
        //   permission: "all_report",
        //   isChild: true,
        // },
        {
          id: "general_aggregator",
          title: "general_aggregator",
          path: "/home/reports/general_aggregator",
          isActive: false,
          permission: "reports_general_aggregator",
          isChild: true,
        },
        {
          id: "operator_report_order",
          title: "operator_report_order",
          path: "/home/reports/operator_report",
          isActive: false,
          permission: "operator_report",
          isChild: true,
        },
        {
          id: "dashboard_report",
          title: "dashboard_report",
          path: "/home/reports/dashboard_report",
          isActive: false,
          permission: "reports_dashboard",
          isChild: true,
        },
        {
          id: "branch_report",
          title: "branch_report",
          path: "/home/reports/branch_report",
          isActive: false,
          permission: "branch_report",
          isChild: true,
        },
        {
          id: "reports_by_courier",
          title: "reports.by.courier",
          path: "/home/reports/courier_report",
          isActive: false,
          permission: "report_courier",
          isChild: true,
        },
        {
          id: "product_report",
          title: "product_report",
          path: "/home/reports/product_report",
          isActive: false,
          permission: "report_product",
          isChild: true,
        },
        {
          id: "order_report",
          title: "order_report",
          path: "/home/reports/order_report",
          isActive: false,
          permission: "order_report",
          isChild: true,
        },
        {
          id: "comment_report",
          title: "comment_report",
          path: "/home/reports/comment_report",
          isActive: false,
          permission: "report_comments",
          isChild: true,
        },
        {
          id: "order_status_report",
          title: "order_status_report",
          path: "/home/reports/order_status_report",
          isActive: false,
          permission: "order_status_report",
          isChild: true,
        },
        {
          id: "delivery_time_reports",
          title: "delivery_time_reports",
          path: "/home/reports/delivery_time_reports",
          isActive: false,
          permission: "reports_delivery_time",
          isChild: true,
        },
        {
          id: "forecasting",
          title: "forecasting",
          path: "/home/reports/forecasting",
          isActive: false,
          permission: "reports_forecasting",
          isChild: true,
        },
        {
          id: "customer_report",
          title: "customer_report",
          path: "/home/reports/customer_report",
          isActive: false,
          permission: "reports_customer",
          isChild: true,
        },
        {
          id: "daily_report",
          title: "daily.report",
          path: "/home/reports/daily-report",
          isActive: false,
          permission: "promotion",
          isChild: true,
        },
        {
          id: "external_deliveru_report",
          title: "external.delivery.report",
          path: "/home/reports/external-delivery-report",
          isActive: false,
          permission: "promotion",
          isChild: true,
        },
      ],
    },
    {
      id: "notifications",
      title: "notification",
      path: "/home/notifications",
      isActive: false,
      permission: "notification",
      icon: NotificationsRounded,
    },
  ];

  const settings = [
    {
      id: "settings",
      title: "settings",
      path: "/home/settings",
      isActive: true,
      icon: SettingsRounded,
      redirect: "/home/settings/fares",
      permission: "shipper-setting",
      children: [
        {
          id: "fares",
          title: "fares",
          path: "/home/settings/fares",
          isActive: false,
          permission: "tariff",
          isChild: true,
        },
        {
          id: "integrations",
          title: "integrations",
          path: "/home/settings/integrations",
          isActive: false,
          permission: "integrations",
          isChild: true,
          children: [
            {
              id: "Iiko",
              title: "Iiko",
              path: "/home/settings/integrations/iiko",
              isActive: false,
              permission: "integrations",
              isChild: true,
            },
            {
              id: "jowi",
              title: "Jowi",
              path: "/home/settings/integrations/jowi",
              isActive: false,
              permission: "integrations",
              isChild: true,
            },
            {
              id: "rkeeper",
              title: "RKeeper",
              path: "/home/settings/integrations/rkeeper",
              isActive: false,
              permission: "integrations",
              isChild: true,
            },
            {
              id: "poster",
              title: "Poster",
              path: "/home/settings/integrations/poster",
              isActive: false,
              permission: "integrations",
              isChild: true,
            },
            {
              id: "payme",
              title: "Payme",
              path: "/home/settings/integrations/payme",
              isActive: false,
              permission: "integrations",
              isChild: true,
            },
            {
              id: "click",
              title: "Click",
              path: "/home/settings/integrations/click",
              isActive: false,
              permission: "integrations",
              isChild: true,
            },
            {
              id: "apelsin",
              title: "Apelsin",
              path: "/home/settings/integrations/apelsin",
              isActive: false,
              permission: "integrations",
              isChild: true,
            },
            {
              id: "sms",
              title: "SMS",
              path: "/home/settings/integrations/sms",
              isActive: false,
              permission: "integrations",
              isChild: true,
            },
            {
              id: "yandex",
              title: "Яндекс доставка",
              path: "/home/settings/integrations/yandex-delivery",
              isActive: false,
              permission: "integrations",
              isChild: true,
            },
          ],
        },
        {
          id: "aggregator",
          title: "aggregator",
          path: "/home/settings/aggregator",
          isActive: false,
          permission: "shipper-setting",
          isChild: true,
        },
        {
          id: "user-roles",
          title: "user-roles",
          path: "/home/settings/user-roles",
          isActive: false,
          permission: "role_permission",
          isChild: true,
        },
        {
          id: "company",
          title: "company",
          path: "/home/settings/company",
          isActive: false,
          permission: "company",
          isChild: true,
        },
        {
          id: "bot-settings",
          title: "bot-settings",
          path: "/home/settings/bot-settings",
          isActive: false,
          permission: "company",
          isChild: true,
        },
        {
          id: "content-settings",
          title: "ContentSettings",
          path: "/home/settings/content-settings",
          isActive: false,
          permission: "company",
          isChild: true,
        },
        {
          id: "content",
          title: "content",
          redirect: "/home/settings/content/reviews",
          isActive: false,
          permission: "reviews",
          isChild: true,
          children: [
            {
              id: "reviews",
              title: "reviews",
              path: "/home/settings/content/reviews",
              isActive: false,
              permission: "reviews",
              isChild: true,
            },
            {
              id: "cancel-reasons",
              title: "cancel-reasons",
              path: "/home/settings/content/cancel-reasons",
              isActive: false,
              permission: "cancel_reason",
              isChild: true,
            },
            {
              id: "completion-reasons",
              title: "completion-reasons",
              path: "/home/settings/content/completion-reasons",
              isActive: false,
              permission: "completion_reasons",
              isChild: true,
            },
          ],
        },
        {
          id: "balance",
          title: "balance",
          path: "/home/settings/balance",
          isActive: false,
          permission: "balance",
          isChild: true,
        },
        {
          id: "Discounts",
          title: "Discounts",
          path: "/home/settings/discounts",
          isActive: false,
          permission: "discounts",
          isChild: true,
        },
        {
          id: "sms_template",
          title: "SMSTemplate",
          path: "/home/settings/sms-template",
          isActive: false,
          permission: "discounts",
          isChild: true,
        },
      ],
    },
  ];

  const account = [
    {
      id: "account",
      title: `${name ?? "personal.profile"} `,
      path: "/home/account",
      isActive: true,
      icon: AccountCircleRounded,
      permission: "profile",
    },
  ];

  return { account, settings, menu };
};

export default useSidebarElements;
